# Generated by Django 5.2.4 on 2025-08-17 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Flat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "bhk",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "1 BHK"),
                            (2, "2 BHK"),
                            (3, "3 BHK"),
                            (4, "4 BHK"),
                            (5, "5 BHK or more"),
                        ]
                    ),
                ),
                ("bathrooms", models.PositiveSmallIntegerField(default=1)),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("unfurnished", "Unfurnished"),
                            ("semi-furnished", "Semi-Furnished"),
                            ("fully-furnished", "Fully Furnished"),
                        ],
                        default="unfurnished",
                        max_length=20,
                    ),
                ),
                (
                    "area_sqft",
                    models.PositiveIntegerField(help_text="Total area in square feet"),
                ),
                ("rent", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "deposit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("available_from", models.DateField()),
                ("is_available", models.BooleanField(default=True)),
                ("address", models.CharField(max_length=300)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("parking", models.BooleanField(default=False)),
                ("lift", models.BooleanField(default=False)),
                ("security", models.BooleanField(default=False)),
                ("power_backup", models.BooleanField(default=False)),
                ("gym", models.BooleanField(default=False)),
                ("swimming_pool", models.BooleanField(default=False)),
                ("wifi", models.BooleanField(default=False)),
                ("pets_allowed", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="flat_images/"),
                ),
                ("listed_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "listed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-listed_on"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("booked_on", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "boarder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="Flat.flat",
                    ),
                ),
            ],
        ),
    ]
