# Generated by Django 5.2.4 on 2025-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_boarder',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_landlord',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('boarder', 'Boarder')], default='boarder', max_length=50),
        ),
    ]
