# Generated by Django 5.2.4 on 2025-07-27 17:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[accounts.models.User.validate_phone],
                verbose_name="Phone Number",
            ),
        ),
    ]
