# Generated by Django 5.2.4 on 2025-07-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("landlord", "Landlord"), ("boarder", "Boarder")],
                default="boarder",
                max_length=50,
                null=True,
            ),
        ),
    ]
