# Generated by Django 5.2.4 on 2025-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
