# Generated by Django 5.2.3 on 2025-06-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PG', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pglisting',
            name='room_type',
            field=models.CharField(choices=[('ac', 'AC'), ('non_ac', 'non_AC')], default='non_ac'),
        ),
        migrations.AlterField(
            model_name='pglisting',
            name='sharing_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('triple', 'Triple')], default=1),
        ),
    ]
